version: '3'

services:
  app_los_ciruelos:
    build: Seminario
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://los_ciruelos:3306/los_ciruelos?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USERNAME: root
      DB_PASSWORD: 1234
      FIREBASE_CREDENTIALS_PATH: /app/firebase_credentials.json  # Ruta dentro del contenedor
    restart: always
    depends_on:
      los_ciruelos:
        condition: service_healthy
    volumes:
      - ./Seminario/src/main/resources/firebase_credentials.json:/app/firebase_credentials.json  # Monta el archivo JSON

  los_ciruelos:
    image: mysql:8.0.33
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: los_ciruelos
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
    volumes:
      - ./Seminario/src/main/resources/data.sql:/docker-entrypoint-initdb.d/data.sql  # Mapea el script SQL
